const doctors=[
{id:1,name:"د. سيف الهاشمي - تجريبي",gov:"النجف",spec:"أطفال",summary:"ظهر اسمه بكثافة ضمن العينة التجريبية، مع تكرار واضح في الترشيحات المباشرة.",stats:{sampleSize:80,mentions:56,directRecommendations:41,rank:1,totalCompared:8},sourceBreakdown:[{label:"فيسبوك",count:34},{label:"إنستغرام",count:12},{label:"خرائط",count:6},{label:"أخرى",count:4}],researchRounds:[{label:"جولة 1",mentions:31},{label:"جولة 2",mentions:40},{label:"جولة 3",mentions:49},{label:"جولة 4",mentions:56}],findings:["الأعلى في مرات الذكر داخل البيانات التجريبية.","الترشيحات المباشرة تشكل نسبة مرتفعة من العينة.","البيانات هنا وهمية لاختبار العرض فقط."]},
{id:2,name:"د. مروان الكعبي - تجريبي",gov:"النجف",spec:"أطفال",summary:"حضور قوي في نتائج البحث التجريبية، لكنه أقل من الطبيب الأول في الترشيحات المباشرة.",stats:{sampleSize:80,mentions:49,directRecommendations:32,rank:2,totalCompared:8},sourceBreakdown:[{label:"فيسبوك",count:29},{label:"إنستغرام",count:9},{label:"خرائط",count:8},{label:"أخرى",count:3}],researchRounds:[{label:"جولة 1",mentions:25},{label:"جولة 2",mentions:33},{label:"جولة 3",mentions:42},{label:"جولة 4",mentions:49}],findings:["ثاني أعلى اسم في المثال التجريبي.","حضور متوازن بين أكثر من مصدر."]},
{id:3,name:"د. علياء الموسوي - تجريبي",gov:"النجف",spec:"جلدية",summary:"نتيجة تجريبية متوسطة إلى مرتفعة مع حضور رقمي واضح.",stats:{sampleSize:70,mentions:43,directRecommendations:29,rank:3,totalCompared:8},sourceBreakdown:[{label:"فيسبوك",count:20},{label:"إنستغرام",count:15},{label:"خرائط",count:5},{label:"أخرى",count:3}],researchRounds:[{label:"جولة 1",mentions:18},{label:"جولة 2",mentions:27},{label:"جولة 3",mentions:35},{label:"جولة 4",mentions:43}],findings:["الحضور الرقمي واضح في المثال.","الترشيحات المباشرة أقل من أول اسمين."]},
{id:4,name:"د. كرار الجبوري - تجريبي",gov:"النجف",spec:"قلب",summary:"اسم متكرر في العينة التجريبية مع نسبة ترشيحات مستقرة.",stats:{sampleSize:65,mentions:36,directRecommendations:24,rank:4,totalCompared:8},sourceBreakdown:[{label:"فيسبوك",count:18},{label:"إنستغرام",count:6},{label:"خرائط",count:9},{label:"أخرى",count:3}],researchRounds:[{label:"جولة 1",mentions:15},{label:"جولة 2",mentions:22},{label:"جولة 3",mentions:29},{label:"جولة 4",mentions:36}],findings:["نتيجة متوسطة ضمن المثال.","جزء جيد من الظهور جاء من الخرائط."]},
{id:5,name:"د. زهراء التميمي - تجريبي",gov:"النجف",spec:"نسائية",summary:"ظهور متوسط مع تركز نسبي في المصادر الاجتماعية.",stats:{sampleSize:60,mentions:31,directRecommendations:20,rank:5,totalCompared:8},sourceBreakdown:[{label:"فيسبوك",count:17},{label:"إنستغرام",count:8},{label:"خرائط",count:4},{label:"أخرى",count:2}],researchRounds:[{label:"جولة 1",mentions:14},{label:"جولة 2",mentions:19},{label:"جولة 3",mentions:25},{label:"جولة 4",mentions:31}],findings:["ترشيحات متوسطة ضمن العينة التجريبية.","المصادر الاجتماعية تمثل الجزء الأكبر من الظهور."]},
{id:6,name:"د. حيدر الساعدي - تجريبي",gov:"الكوفة",spec:"باطنية",summary:"نتيجة تجريبية أقل من المتوسط لكنها مستقرة عبر الجولات.",stats:{sampleSize:55,mentions:25,directRecommendations:16,rank:6,totalCompared:8},sourceBreakdown:[{label:"فيسبوك",count:11},{label:"إنستغرام",count:4},{label:"خرائط",count:8},{label:"أخرى",count:2}],researchRounds:[{label:"جولة 1",mentions:12},{label:"جولة 2",mentions:16},{label:"جولة 3",mentions:21},{label:"جولة 4",mentions:25}],findings:["النمو عبر جولات البحث تدريجي.","حضور الخرائط ملحوظ نسبيًا."]},
{id:7,name:"د. نور العبيدي - تجريبي",gov:"الكوفة",spec:"جلدية",summary:"ظهور محدود نسبيًا داخل العينة الوهمية.",stats:{sampleSize:50,mentions:19,directRecommendations:11,rank:7,totalCompared:8},sourceBreakdown:[{label:"فيسبوك",count:9},{label:"إنستغرام",count:5},{label:"خرائط",count:4},{label:"أخرى",count:1}],researchRounds:[{label:"جولة 1",mentions:8},{label:"جولة 2",mentions:12},{label:"جولة 3",mentions:15},{label:"جولة 4",mentions:19}],findings:["الحضور أقل من الأسماء السابقة في المثال.","هذه ليست بيانات حقيقية."]},
{id:8,name:"د. مهند الشمري - تجريبي",gov:"النجف",spec:"عظام",summary:"أقل نتيجة ضمن المثال الحالي حتى يظهر فرق واضح في الرسوم.",stats:{sampleSize:45,mentions:13,directRecommendations:7,rank:8,totalCompared:8},sourceBreakdown:[{label:"فيسبوك",count:6},{label:"إنستغرام",count:2},{label:"خرائط",count:4},{label:"أخرى",count:1}],researchRounds:[{label:"جولة 1",mentions:5},{label:"جولة 2",mentions:8},{label:"جولة 3",mentions:10},{label:"جولة 4",mentions:13}],findings:["أقل تكرارًا في البيانات التجريبية الحالية.","وضعناه عمدًا حتى نشوف الفروقات بصريًا."]}
];